# Generated by Django 4.2.3 on 2023-07-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principio_ativo', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('codigo_ggrem', models.CharField(max_length=100)),
                ('registro', models.CharField(max_length=100)),
                ('ean1', models.CharField(max_length=100)),
                ('produto', models.CharField(max_length=100)),
                ('apresentacao', models.CharField(max_length=100)),
                ('classe_terapeutica', models.CharField(max_length=100)),
                ('tipo_produto', models.CharField(max_length=100)),
                ('regime_preco', models.CharField(max_length=100)),
                ('pf_sem_impostos', models.CharField(max_length=100)),
                ('pf_0_percent', models.CharField(max_length=100)),
                ('pf_12_percent', models.CharField(max_length=100)),
                ('pf_17_percent', models.CharField(max_length=100)),
                ('pf_17_alc', models.CharField(max_length=100)),
                ('pf_175_percent', models.CharField(max_length=100)),
                ('pf_175_alc', models.CharField(max_length=100)),
                ('pf_18_percent', models.CharField(max_length=100)),
                ('pf_18_alc', models.CharField(max_length=100)),
                ('pf_19_percent', models.CharField(max_length=100)),
                ('pf_20_percent', models.CharField(max_length=100)),
                ('pf_21_percent', models.CharField(max_length=100)),
                ('pf_22_percent', models.CharField(max_length=100)),
                ('pmvg_sem_impostos', models.CharField(max_length=100)),
                ('pmvg_0_percent', models.CharField(max_length=100)),
                ('pmvg_12_percent', models.CharField(max_length=100)),
                ('pmvg_17_percent', models.CharField(max_length=100)),
                ('pmvg_17_alc', models.CharField(max_length=100)),
                ('pmvg_175_percent', models.CharField(max_length=100)),
                ('pmvg_175_alc', models.CharField(max_length=100)),
                ('pmvg_18_percent', models.CharField(max_length=100)),
                ('pmvg_18_alc', models.CharField(max_length=100)),
                ('pmvg_19_percent', models.CharField(max_length=100)),
                ('pmvg_20_percent', models.CharField(max_length=100)),
                ('pmvg_21_percent', models.CharField(max_length=100)),
                ('pmvg_22_percent', models.CharField(max_length=100)),
                ('restricao_hospitalar', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=100)),
                ('confaz_87', models.CharField(max_length=100)),
                ('icms_0_percent', models.CharField(max_length=100)),
                ('analise_recursal', models.CharField(max_length=100)),
                ('lista_concessao_credito', models.CharField(max_length=100)),
                ('comercializacao_2022', models.CharField(max_length=100)),
                ('tarja', models.CharField(max_length=100)),
            ],
        ),
    ]
