# Generated by Django 4.2.3 on 2023-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='selecionado',
            field=models.BooleanField(default=False),
        ),
    ]
